{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "my-new-helm.serviceAccountName" . }}
  labels:
{{ include "my-new-helm.labels" . | indent 4 }}
{{- end -}}
